<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'cCoder.Workflow.Activities'">
    <PackageReference Include="cCoder.CodeAnalysis" Version="2026.9.13.1655" PrivateAssets="all" />
  </ItemGroup>
</Project>
