<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'cCoder.Workflow.Activities'">
    <PackageReference Include="cCoder.CodeAnalysis" Version="2026.9.29.1241" IncludeAssets="analyzers;build;buildTransitive" PrivateAssets="all" />
    <PackageReference Include="cCoder.CodeAnalysis.Contracts" Version="2026.9.29.1241" />
  </ItemGroup>
</Project>
